### ISSUE TITLE
GMRF Skyride test XML fails during initialization.

### ISSUE THREAD

**Issue by tgvaughan** [BEAST2-Dev/beast-classic#6]
Here's the stack trace:
```
java.lang.NullPointerException
	at beast.evolution.tree.coalescent.GMRFSkyrideLikelihood.getCorrectFieldLength(Unknown Source)
	at beast.evolution.tree.coalescent.GMRFSkyrideLikelihood.initAndValidate(Unknown Source)
	at beast.util.XMLParser.initBEASTObjects(Unknown Source)
	at beast.util.XMLParser.parse(Unknown Source)
	at beast.util.XMLParser.parseFile(Unknown Source)
	at beast.app.BeastMCMC.parseArgs(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)

Error 110 parsing the xml input file

validate and intialize error: null

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <distribution id='posterior' spec='util.CompoundDistribution'>
              <distribution id='prior' spec='util.CompoundDistribution'>
                  <distribution id='skyride' spec='beast.evolution.tree.coalescent.GMRFSkyrideLikelihood'>
```

**Comment by tgvaughan** [comment]
Looking at the code, it seems that `GMRFSkyrideLikelihood` extends `TreeDistribution`, which allows either a "tree" input or the "treeIntervals" input to be given.  However `GMRFSkyrideLikelihood` seems to assume "tree" is specified, while in the test XML only "treeIntervals" is specified.  Interestingly, `GMRFSkyrideLikelihood::initAndValidate` has some commented-out code that in the past raised an exception when "tree" was not specified. 

Simply replacing the treeIntervals input in the XML with a tree may be enough to fix this, but I'm curious as to how this happened.  (There was a tree input specified already in the test XML, but commented out.)
